// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestRouterMvvm.Data;

#nullable disable

namespace TestRouterMvvm.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251218075019_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("DBCharacterDBScenario", b =>
                {
                    b.Property<int>("ChatsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DBCharactersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChatsId", "DBCharactersId");

                    b.HasIndex("DBCharactersId");

                    b.ToTable("DBCharacterDBScenario");
                });

            modelBuilder.Entity("TestRouterMvvm.Models.Database.DBAIModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AIModels");
                });

            modelBuilder.Entity("TestRouterMvvm.Models.Database.DBCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMature")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Persona")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("TestRouterMvvm.Models.Database.DBScenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanDeleteExampleMessages")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExampleMessages")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FormattingInstructions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Grammar")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinP")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MinPEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Narrative")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PromptTemplate")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("RepeatLastN")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RepeatPenalty")
                        .HasColumnType("TEXT");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Temperature")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TopK")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TopP")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.HasIndex("ScenarioId");

                    b.ToTable("Scenarios");
                });

            modelBuilder.Entity("TestRouterMvvm.Models.Database.DBUserPersona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Persona")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserPersonas");
                });

            modelBuilder.Entity("TestRouterMvvm.Models.Database.EFKeyValuePair<string, string>", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DBCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasIndex("DBCharacterId");

                    b.ToTable("EFKeyValuePair<string, string>");
                });

            modelBuilder.Entity("DBCharacterDBScenario", b =>
                {
                    b.HasOne("TestRouterMvvm.Models.Database.DBScenario", null)
                        .WithMany()
                        .HasForeignKey("ChatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestRouterMvvm.Models.Database.DBCharacter", null)
                        .WithMany()
                        .HasForeignKey("DBCharactersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestRouterMvvm.Models.Database.DBScenario", b =>
                {
                    b.HasOne("TestRouterMvvm.Models.Database.DBAIModel", "Model")
                        .WithMany("DBScenarios")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestRouterMvvm.Models.Database.DBUserPersona", "DBUserPersona")
                        .WithMany("DBScenarios")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DBUserPersona");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("TestRouterMvvm.Models.Database.EFKeyValuePair<string, string>", b =>
                {
                    b.HasOne("TestRouterMvvm.Models.Database.DBCharacter", null)
                        .WithMany("Lorebook")
                        .HasForeignKey("DBCharacterId");
                });

            modelBuilder.Entity("TestRouterMvvm.Models.Database.DBAIModel", b =>
                {
                    b.Navigation("DBScenarios");
                });

            modelBuilder.Entity("TestRouterMvvm.Models.Database.DBCharacter", b =>
                {
                    b.Navigation("Lorebook");
                });

            modelBuilder.Entity("TestRouterMvvm.Models.Database.DBUserPersona", b =>
                {
                    b.Navigation("DBScenarios");
                });
#pragma warning restore 612, 618
        }
    }
}
